import { jsPDF } from "jspdf";
import { formatCurrency, formatDate, titleCase } from "./format";

const NAVY = [22, 50, 50];
const GOLD = [180, 83, 9];
const MUTED = [110, 120, 135];

/**
 * Generates a printable guest statement PDF: profile summary plus every
 * booking on record with its own line, closing with total revenue
 * generated by this guest. Mirrors `invoicePdf.js`'s layout conventions
 * for visual consistency between the two document types.
 */
export function downloadGuestStatementPdf(guestProfile) {
  const { user, bookings, totalSpent, activeBookingsCount } = guestProfile;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Grand Horizon Hotel", margin, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(212, 167, 44);
  doc.text("GUEST STATEMENT", margin, 62);

  doc.setTextColor(230, 230, 235);
  doc.setFontSize(9);
  doc.text(formatDate(new Date().toISOString()), pageWidth - margin, 42, { align: "right" });

  let y = 132;
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(user.name || "Guest", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(user.email || "", margin, y);
  y += 14;
  doc.text(user.phone || "", margin, y);

  const rightColX = pageWidth / 2 + 20;
  let ry = 132;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text("Account Summary", rightColX, ry);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  ry += 16;
  doc.text(`Joined: ${formatDate(user.createdAt)}`, rightColX, ry);
  ry += 14;
  doc.text(`Total Bookings: ${bookings.length}`, rightColX, ry);
  ry += 14;
  doc.text(`Active Reservations: ${activeBookingsCount}`, rightColX, ry);

  y = Math.max(y, ry) + 32;
  doc.setDrawColor(230, 232, 236);
  doc.line(margin, y, pageWidth - margin, y);
  y += 26;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("RESERVATION", margin, y);
  doc.text("DATES", margin + 160, y);
  doc.text("STATUS", margin + 300, y);
  doc.text("AMOUNT", pageWidth - margin, y, { align: "right" });
  y += 10;
  doc.setDrawColor(230, 232, 236);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);

  if (bookings.length === 0) {
    doc.setTextColor(...MUTED);
    doc.text("No bookings on record.", margin, y);
    y += 20;
  }

  bookings.forEach((booking) => {
    if (y > pageHeight - 100) {
      doc.addPage();
      y = 60;
    }
    doc.setTextColor(...NAVY);
    doc.text(booking.bookingReference || "—", margin, y);
    doc.setTextColor(...MUTED);
    doc.text(`${formatDate(booking.checkInDate)} - ${formatDate(booking.checkOutDate)}`, margin + 160, y);
    doc.text(titleCase(booking.status), margin + 300, y);
    doc.setTextColor(...NAVY);
    doc.text(formatCurrency(booking.totalAmount), pageWidth - margin, y, { align: "right" });
    y += 20;
  });

  y += 6;
  doc.setDrawColor(230, 232, 236);
  doc.line(margin, y, pageWidth - margin, y);
  y += 26;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text("Total Revenue (excl. cancelled)", margin, y);
  doc.setTextColor(...GOLD);
  doc.text(formatCurrency(totalSpent), pageWidth - margin, y, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text("Generated by Grand Horizon Hotel Admin Portal.", margin, pageHeight - 40);

  doc.save(`guest-statement-${(user.name || "guest").toLowerCase().replace(/\s+/g, "-")}.pdf`);
}
